databases:
  - name: kaidan_DB
    databaseName: kaidan_db_4tg2
    user: kaidan
    region: singapore

services:
  - type: web
    name: kaidan
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kaidan_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

